// nextjs/src/layouts/default.jsx
import TheNavBar from "../components/common/TheNavBar";
import TheFooter from "../components/common/TheFooter";
import {Container} from "@chakra-ui/react";

export default function DefaultLayout({children}) {
  return (
      <>
        <TheNavBar/>
        <Container>
          <main>{children}</main>
        </Container>
        <TheFooter/>
      </>
  )
}

// nuxt3/src/layouts/default.vue
<template>
  <main class="min-h-screen">
    <TheHeader/>
    <main class="min-h-[70vh] mb-10">
      <slot></slot>
    </main>
    <TheFooter/>
  </main>
</template>

<script setup lang="ts">
import TheHeader from "~/components/common/TheHeader.vue";
import TheFooter from "~/components/common/TheFooter.vue";
</script>
